[[headers]]
  for = "/.well-known/stellar.toml"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Redirect HTTP to HTTPS (removing 'force = true' to avoid conflicts)
[[redirects]]
  from = "http://trumpstellar.digital/*"
  to = "https://trumpstellar.digital/:splat"
  status = 301
