[[headers]]
  for = "/.well-known/stellar.toml"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Content-Type = "text/plain; charset=utf-8"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[[redirects]]
  from = "http://trumpstellar.digital/*"
  to = "https://trumpstellar.digital/:splat"
  status = 301
  force = true

  [[headers]]
  for = "/.well-known/stellar.toml"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"